# Generated by Django 2.1.7 on 2019-10-27 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0002_tutorial_uploaded_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutorial',
            name='feature_image',
        ),
    ]
