# Generated by Django 2.1.7 on 2019-10-27 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0003_remove_tutorial_feature_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorial',
            name='upload_user',
            field=models.CharField(default='dungth1', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='category',
            field=models.CharField(choices=[('CDD', 'CDD'), ('PCM', 'PCM')], max_length=100),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='title',
            field=models.CharField(choices=[('DHML', 'Phòng ĐHML'), ('TKTU', 'Phòng TKTU'), ('DD', 'Phòng Di Động')], max_length=100),
        ),
    ]
