# Generated by Django 2.1.7 on 2019-10-29 11:44

from django.db import migrations, models
import tutorials.models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0004_auto_20191027_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='attachment',
            field=models.FileField(upload_to=tutorials.models.linkto),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='title',
            field=models.CharField(choices=[('DHML_DEPT', 'PHÒNG ĐIỀU HÀNH MẠNG LƯỚI'), ('TKTU_DEPT', 'PHÒNG THIẾT KẾ TỐI ƯU'), ('DD_DEPT', 'PHÒNG DI ĐỘNG')], max_length=100),
        ),
    ]
