# Generated by Django 2.1.7 on 2019-10-29 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0005_auto_20191029_1844'),
    ]

    operations = [
        migrations.CreateModel(
            name='approve',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approve_status', models.CharField(choices=[('Y', 'OK'), ('N', 'NOK'), ('W', 'Waiting')], max_length=100)),
                ('attachment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutorials.Tutorial')),
            ],
        ),
    ]
