# Generated by Django 2.1.7 on 2019-10-29 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0007_tutorial_approve_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='approve',
            name='attachment',
        ),
    ]
