# Generated by Django 2.1.7 on 2019-10-29 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0008_remove_approve_attachment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='approve',
        ),
    ]
