# Generated by Django 2.1.7 on 2019-10-29 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0010_auto_20191029_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='approve_status',
            field=models.CharField(choices=[('Y', 'OK'), ('N', 'NOK'), ('W', 'Waiting')], default='Waiting', max_length=100),
        ),
    ]
