# Generated by Django 2.1.7 on 2019-10-29 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0012_auto_20191029_2043'),
    ]

    operations = [
        migrations.CreateModel(
            name='Approve',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approve_status', models.CharField(choices=[('Y', 'OK'), ('N', 'NOK'), ('W', 'Waiting')], default='W', max_length=100)),
            ],
        ),
    ]
