# Generated by Django 2.1.7 on 2019-10-29 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0013_approve'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Approve',
        ),
    ]
