# Generated by Django 2.1.7 on 2019-10-30 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0015_approve'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Approve',
        ),
    ]
