# Generated by Django 2.1.7 on 2019-10-30 04:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0016_delete_approve'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorial',
            name='approved_user',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
