# Generated by Django 2.1.7 on 2019-10-30 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0018_tutorial_phuongan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tutorial',
            old_name='title',
            new_name='dept',
        ),
    ]
